from __future__ import annotations

NARRATIVE_CLAIM_ONTOLOGY_VERSION = "1.0.0"

NARRATIVE_CLAIM_FAMILIES: dict[str, str] = {
    "project_identity": "Project naming and identity fields.",
    "customer_identity": "Customer and end-customer naming fields.",
    "request_context": "Request source and intake context.",
    "business_driver": "Business motivation and success intent.",
    "project_summary": "High-level narrative project description.",
    "success_criteria": "Explicit completion outcomes.",
    "site_count_claim": "Explicit or strongly supported site count.",
    "site_location_claim": "Site location names, addresses, and geography.",
    "site_type_claim": "Site type and profile labels.",
    "site_topology_claim": "Building/floor/MDF/IDF/topology references.",
    "site_condition_claim": "Observed site conditions and constraints.",
    "scope_included_claim": "In-scope tasks and workstream items.",
    "scope_excluded_claim": "Out-of-scope statements.",
    "scope_by_others_claim": "By-others ownership statements.",
    "known_quantity_claim": "Quantities and units.",
    "technical_environment_claim": "Current/target technical environment and dependencies.",
    "schedule_claim": "Dates, milestones, cutover, blackout windows.",
    "access_logistics_claim": "Access constraints and logistics conditions.",
    "deliverable_claim": "Deliverables and output artifacts.",
    "testing_acceptance_claim": "Testing requirements and acceptance basis.",
    "customer_responsibility_claim": "Customer-owned tasks and responsibilities.",
    "customer_input_required_claim": "Inputs customer must provide.",
    "customer_document_required_claim": "Required customer docs.",
    "customer_material_claim": "Customer-provided materials/equipment.",
    "third_party_dependency_claim": "External dependency constraints.",
    "commercial_structure_claim": "Commercial model and billing constraints.",
    "assumption_claim": "Assumptions and prerequisite conditions.",
    "risk_claim": "Risk statements and uncertainty signals.",
    "open_question_claim": "Questions needing resolution.",
    "readiness_gap_claim": "Readiness blockers and gaps.",
    "contact_claim": "Primary customer contact details.",
    "decision_maker_claim": "Decision-maker references.",
    "sow_author_note_claim": "Author guidance notes for final SOW drafting.",
}
