"""End-to-end demo runner — reproducible from code alone.

What this script proves: given the parser-os repo + the
Orbitbrief-Core repo + a working Ollama, every artifact the FE
engineer reads (PM_HANDOFF.json, SOW_DRAFT.md, RFP_DRAFT.md,
polish_report.json, the full stage-by-stage substrate dump) is
generated by code with no manual editing.

Run::

    export PARSER_OS_ROOT=/path/to/parser-os
    export OLLAMA_BASE_URL=http://localhost:11434   # or remote
    python tools/demo_end_to_end.py

    # → /tmp/orbitbrief_demo/<case>/
    #     ├── PM_HANDOFF.json
    #     ├── PM_HANDOFF.md / .html
    #     ├── SOW_DRAFT.md
    #     ├── polish_report.json
    #     ├── pipeline_log.json
    #     ├── 00_envelope.json
    #     ├── 10..81_*.json
    #     └── (all stage outputs)

Then a contract assertion confirms PM_HANDOFF.json has the shape the
FE engineer's pm-handoff-types.ts expects.

Picks ``COPPER_001_SPRING_LAKE_AUDITORIUM`` from parser-os'
``real_data_cases/`` by default — a real committed case. Pass
``--case <name>`` to use a different one.
"""
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CASE = "COPPER_001_SPRING_LAKE_AUDITORIUM"
DEFAULT_OUT = Path("/tmp/orbitbrief_demo") if os.name != "nt" else Path("C:/tmp/orbitbrief_demo")

# Fields the FE engineer's pm-handoff-types.ts requires.
# Asserted post-run to prove the contract holds.
REQUIRED_TOPLEVEL_FIELDS = [
    "case_id", "status", "status_label", "one_line_summary", "metrics",
    "domains", "sites", "gaps", "facts_by_category", "source_files",
    "customer_questions", "money_mentions", "reconciliation_flags",
    "risk_register", "schedule_phases", "site_rollups", "site_allocations",
    "action_items", "stakeholder_pagers", "compliance_callouts",
    "rfp_line_items", "executive_summary", "stakeholder_contacts",
    "exclusions", "responsibilities", "margin_view", "engagement_model",
    "license_items", "currency_mentions", "tax_clauses",
    "subcontractor_mentions", "sla_penalties", "risk_aging",
    "intake_completeness", "currency_conversions", "eol_flags",
    "comparable_deals", "ocr_backend_status", "crm_detections",
    "sow_draft_markdown", "rfp_draft_markdown", "parser_quality_score",
    "run_telemetry", "drift_snapshot", "urgency_signals",
    "customer_answer_slots",
]


def _say(msg: str) -> None:
    print(f"[>] {msg}", flush=True)


def _ok(msg: str) -> None:
    print(f"[OK] {msg}", flush=True)


def _bad(msg: str) -> None:
    print(f"[!!] {msg}", flush=True)


def _resolve_parser_os() -> Path:
    env_path = os.environ.get("PARSER_OS_ROOT")
    if env_path:
        p = Path(env_path).expanduser().resolve()
        if not p.is_dir():
            _bad(f"PARSER_OS_ROOT set but not a directory: {p}")
            sys.exit(2)
        return p
    # Try a few common locations
    for guess in [
        REPO_ROOT.parent / "parser-os",
        REPO_ROOT.parent / "parser-os-repo",
        Path.home() / "parser-os",
    ]:
        if guess.is_dir():
            return guess
    _bad("PARSER_OS_ROOT not set and parser-os not found in common locations.")
    _bad("Set PARSER_OS_ROOT=/abs/path/to/parser-os and rerun.")
    sys.exit(2)


def _check_ollama(base_url: str) -> bool:
    import urllib.request, urllib.error

    try:
        req = urllib.request.Request(f"{base_url}/api/tags", method="GET")
        with urllib.request.urlopen(req, timeout=3) as resp:
            data = json.loads(resp.read())
        models = [m.get("name", "") for m in data.get("models", [])]
        if any(m.startswith("qwen3:14b") for m in models):
            _ok(f"Ollama reachable at {base_url} — qwen3:14b loaded")
            return True
        _bad(f"Ollama reachable at {base_url} but qwen3:14b not installed.")
        _bad("Run: ollama pull qwen3:14b")
        return False
    except (urllib.error.URLError, TimeoutError, OSError) as exc:
        _bad(f"Ollama not reachable at {base_url}: {exc}")
        _bad("Polish stage will skip gracefully and ship raw text.")
        return False


def _run_compile(case_dir: Path, out_dir: Path, *, polish: bool) -> int:
    cmd = [
        sys.executable,
        str(REPO_ROOT / "compile_brief.py"),
        str(case_dir),
        "--out", str(out_dir),
        "--ollama",
        "--quiet-parser",
    ]
    if not polish:
        cmd.append("--no-polish")
    _say(f"running: {' '.join(cmd)}")
    return subprocess.call(cmd)


def _assert_contract(out_dir: Path) -> None:
    _say("verifying PM_HANDOFF.json contract …")
    handoff_path = out_dir / "PM_HANDOFF.json"
    if not handoff_path.exists():
        _bad(f"PM_HANDOFF.json missing at {handoff_path}")
        sys.exit(3)
    h = json.loads(handoff_path.read_text(encoding="utf-8"))
    missing = [f for f in REQUIRED_TOPLEVEL_FIELDS if f not in h]
    if missing:
        _bad(f"PM_HANDOFF.json missing required fields: {missing}")
        sys.exit(3)
    _ok(f"PM_HANDOFF.json has all {len(REQUIRED_TOPLEVEL_FIELDS)} required fields")
    _ok(f"  case_id              = {h['case_id']}")
    _ok(f"  status               = {h['status']}")
    _ok(f"  gaps                 = {len(h['gaps'])} "
        f"(blocker={sum(1 for g in h['gaps'] if g['severity']=='blocker')}, "
        f"warning={sum(1 for g in h['gaps'] if g['severity']=='warning')})")
    _ok(f"  risk_register        = {len(h['risk_register'])}")
    _ok(f"  schedule_phases      = {len(h['schedule_phases'])}")
    _ok(f"  domains              = {len(h['domains'])}")
    _ok(f"  sites                = {len(h['sites'])}")
    _ok(f"  parser_quality       = {h['parser_quality_score'].get('grade')} "
        f"({h['parser_quality_score'].get('score')}/100)")
    _ok(f"  sow_draft (chars)    = {len(h['sow_draft_markdown'])}")
    _ok(f"  rfp_draft (chars)    = {len(h['rfp_draft_markdown'])}")
    _ok(f"  one_line_summary     = {h['one_line_summary'][:80]}...")


def _assert_outputs(out_dir: Path, *, expect_polish: bool) -> None:
    _say("verifying every expected output exists ...")
    expected = [
        "PM_HANDOFF.json",
        "PM_HANDOFF.md",
        "PM_HANDOFF.html",
        "PM_EXECUTIVE_SUMMARY.md",
        "PM_EXECUTIVE_SUMMARY.html",
        "SA_REVIEW_PACKET.md",
        "SA_REVIEW_PACKET.html",
        "SOW_DRAFT.md",
        "pipeline_log.json",
        "manifest.json",
        "00_envelope.json",
        "80_composed_brief.json",
        "81_composed_brief.md",
        "90_inspection_report.json",
    ]
    if expect_polish:
        expected.append("polish_report.json")
    missing = []
    for name in expected:
        path = out_dir / name
        if path.exists():
            _ok(f"  {name:38s} {path.stat().st_size:>10d} bytes")
        else:
            _bad(f"  {name:38s} MISSING")
            missing.append(name)
    if missing:
        sys.exit(3)


def _summarize_polish(out_dir: Path) -> None:
    report_path = out_dir / "polish_report.json"
    if not report_path.exists():
        return
    r = json.loads(report_path.read_text(encoding="utf-8"))
    _say("polish report:")
    _ok(f"  model            = {r.get('model')}")
    _ok(f"  items_total      = {r.get('items_total')}")
    _ok(f"  items_polished   = {r.get('items_polished')}")
    _ok(f"  items_fallback   = {r.get('items_fallback')}")
    _ok(f"  items_cached     = {r.get('items_cached')}")
    _ok(f"  elapsed_ms       = {r.get('elapsed_ms')}")


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--case",
        default=DEFAULT_CASE,
        help=f"Case dir name under parser-os/real_data_cases/ (default: {DEFAULT_CASE})",
    )
    p.add_argument(
        "--out",
        type=Path,
        default=None,
        help=f"Output directory (default: {DEFAULT_OUT}/<case>)",
    )
    p.add_argument(
        "--no-polish",
        action="store_true",
        help="Skip Phase 91 polish (fast substrate-only run, ~6 s on a small case)",
    )
    p.add_argument(
        "--keep-existing",
        action="store_true",
        help="Don't wipe the output directory before running",
    )
    args = p.parse_args(argv)

    started = time.monotonic()
    parser_os = _resolve_parser_os()
    case_dir = parser_os / "real_data_cases" / args.case
    if not case_dir.is_dir():
        _bad(f"case dir not found: {case_dir}")
        return 2
    _ok(f"parser-os: {parser_os}")
    _ok(f"case:      {case_dir.name}")

    ollama = os.environ.get("OLLAMA_BASE_URL", "http://localhost:11434")
    ollama_ok = _check_ollama(ollama)
    if not args.no_polish and not ollama_ok:
        _say("polish would skip gracefully; running with --no-polish for a clean demo")
        polish = False
    else:
        polish = not args.no_polish

    out_dir = args.out or (DEFAULT_OUT / args.case)
    if out_dir.exists() and not args.keep_existing:
        shutil.rmtree(out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    _ok(f"out:       {out_dir}")

    os.environ.setdefault("PARSER_OS_ROOT", str(parser_os))
    rc = _run_compile(case_dir, out_dir, polish=polish)
    if rc != 0:
        _bad(f"compile_brief exited {rc}")
        return rc

    _assert_outputs(out_dir, expect_polish=polish)
    _assert_contract(out_dir)
    if polish:
        _summarize_polish(out_dir)

    elapsed = time.monotonic() - started
    print()
    _ok(f"DEMO COMPLETE in {elapsed:.1f} s — all outputs in {out_dir}")
    print()
    print(f"Next step for the FE engineer:")
    print(f"  - read {out_dir}/PM_HANDOFF.json")
    print(f"  - match every field against handoff_bundle/pm-handoff-types.ts")
    print()
    print(f"Next step for the Azure engineer:")
    print(f"  - read {out_dir}/polish_report.json to confirm polish ran")
    print(f"  - read {out_dir}/pipeline_log.json for per-stage telemetry")
    print(f"  - the same command in a Container Apps job is the production path")
    return 0


if __name__ == "__main__":
    sys.exit(main())
